const API_KEY = {
	LIST: '/list',
	PRODUCT: '/product',
	INFO: '/info',
	POPULAR: '/popular',
	SELL: '/sell',
	FREE: '/free',
	SHARE: '/share',
	DETAIL: '/detail',
	SEARCH: '/search',
	MYPAGE: '/mypage',
	LIKE: '/like',
	ACCOUNT: '/account',
	PROFILE: '/profile',
	CHAT: '/chat',
	SELLER: '/seller',
	BUYER: '/buyer',
	USER: '/user',
	COUNT: '/count',
	UPDATE: '/update',
	REGISTER: '/register',
	LANDING: '/landing',
}

export default API_KEY
